version: '3.8'
services:
  db:
    image: postgres:15
    container_name: seplag-db
    environment:
      POSTGRES_DB: seplag_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  minio:
    image: minio/minio
    container_name: seplag-minio
    ports:
      - "9000:9000" # API do MinIO
      - "9001:9001" # Console (Interface Web)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"